{
  "name": "{{scope}}{{name}}",
  "version": "{{version}}",
  "description": "> {{description}}",
  "keywords": [
    "{{keywords}}"
  ],
  "browser": "dist/index.umd.js",
  "main": "dist/index.cjs.js",
  "module": "dist/index.esm.js",
  "types": "dist/index.d.ts",
  "files": [
    "dist"
  ],
  "author": "{{author}}<{{email}}>",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "{{repository}}"
  },
  "devDependencies": {
    "@babel/core": "^7.13.14",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.9.0",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-modules-commonjs": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.13.10",
    "@babel/preset-env": "^7.13.12",
    "@commitlint/cli": "^16.2.3",
    "@commitlint/config-conventional": "^16.2.1",
    "@rollup/plugin-alias": "^3.0.1",
    "@rollup/plugin-babel": "^5.2.1",
    "@rollup/plugin-commonjs": "^18.0.0",
    "@rollup/plugin-node-resolve": "^11.2.1",
    "@rollup/plugin-replace": "^2.4.2",
    "@ufly/sam": "^1.0.1",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.1.0",
    "clean-before-html-webpack-plugin": "^1.0.1",
    "console-log-h5": "^1.1.1",
    "conventional-changelog-cli": "^2.1.1",
    "coveralls": "^3.1.0",
    "cross-env": "^7.0.2",
    "css-loader": "^5.2.0",
    "eslint": "^7.23.0",
    "eslint-loader": "^4.0.2",
    "html-webpack-plugin": "^5.3.1",
    "husky": "^7.0.4",
    "jest": "^26.6.3",
    "lint-staged": "^12.3.7",
    "lodash": "^4.17.15",
    "mini-css-extract-plugin": "^1.4.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.4.1",
    "rollup": "^2.44.0",
    "sass": "^1.32.8",
    "sass-loader": "11.0.1",
    "standard-version": "^9.1.1",
    "style-loader": "^2.0.0",
    "typescript": "^4.2.3",
    "webpack": "^5.72.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.8.1",
    "standard-version": "^9.3.2"
  },
  "scripts": {
    "test": "jest --coverage && coveralls < coverage/lcov.info",
    "i": "yarn install -s --force",
    "dev": "cross-env HTTPS=1 sam webpack serve --mode=development",
    "release": "standard-version -r patch",
    "beta": "standard-version --skip.tag --prerelease beta",
    "alpha": "standard-version --skip.tag --prerelease alpha",
    "build": "rm -rf dist && run-p test build:pkg build:types && rm ./dist/index.js",
    "build:pkg": "rollup -c --silent",
    "build:demo": "cross-env NODE_ENV=production webpack --mode=production",
    "build:types": "tsc",
    "postalpha": "npm publish --tag alpha",
    "postbeta": "npm publish --tag beta",
    "postrelease": "git push --follow-tags origin master && npm publish",
    "preinstall": "rm -rf dist node_modules",
    "postinstall": "husky install"
  },
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org"
  }
}